#ifndef _COMMON_H_
#define _COMMON_H_

#define CRYPTO_PUBLICKEYBYTES_B64 ((CRYPTO_PUBLICKEYBYTES + 2) / 3 * 4) + 1
#define CRYPTO_SECRETKEYBYTES_B64 ((CRYPTO_SECRETKEYBYTES + 2) / 3 * 4) + 1
#define CRYPTO_SHAKEBYTES 32
#define CRYPTO_SHAKEBYTES_B64 ((CRYPTO_SHAKEBYTES + 2) / 3 * 4) + 1
#define CRYPTO_BYTES_B64 ((CRYPTO_BYTES + 2) / 3 * 4) + 1

#endif
