version: '3'
services:
  neo4j:
    image: neo4j:4.2.0
    hostname: neo4j
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./neo4j/plugins:/plugins
      # - ./neo4j/conf:/conf
      - ./neo4j/logs:/logs
    environment:
      NEO4J_AUTH: neo4j/test
